# Generated by Django 5.0.6 on 2024-06-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0002_userguild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=999)),
                ('guild', models.BigIntegerField(max_length=999)),
                ('channel', models.BigIntegerField(max_length=999)),
                ('message', models.BigIntegerField(max_length=999)),
                ('content', models.CharField(max_length=9999)),
                ('reason', models.CharField(max_length=999)),
                ('timestamp', models.DateTimeField()),
                ('attachments', models.ManyToManyField(blank=True, to='moderation_app.attachment')),
            ],
        ),
    ]
