# Generated by Django 5.0.6 on 2024-06-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0003_attachment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='guild',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.BigIntegerField(),
        ),
    ]
