# Generated by Django 5.0.6 on 2024-06-09 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0004_alter_message_channel_alter_message_guild_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='guild',
            field=models.ManyToManyField(blank=True, to='moderation_app.guild'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
