# Generated by Django 5.0.6 on 2024-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0005_remove_message_guild_remove_message_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='messageId',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='channelName',
            field=models.CharField(default='a', max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='userId',
            field=models.BigIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='a', max_length=999),
            preserve_default=False,
        ),
    ]
