# Generated by Django 5.0.6 on 2024-06-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_app', '0007_turnstile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='turnstile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='moderation_app.turnstile'),
        ),
    ]
